### ISSUE TITLE
THANK YOU SO MUCH FOR THIS! (Release section?)

### ISSUE THREAD

**Issue by Cruplezone** [Gericom/GBARunner2#1]
Seriously this is amazing, please continue your work on this! This will be remembered as one of the greatest nds homebrews if it's perfected, runs stable, and has a nice gui! Sending virtual hugs :)

Do you think you could make a release section for newbies to just download, copy and test? Not sure how to compile at all is why I ask all. After copying the bios not sure what to do.

**Comment by Gericom** [comment]
You should download and install the latest devkitpro and run make from the cmd. You may need to create a nitrofiles directory. You should then copy Gbarunner2.nds to your sd card and put a sram patched gba rom as runner.gba on the root of your sd

**Comment by Cruplezone** [comment]
Hm alright one question do I make from within the arm9 directory or from the root directory of this project that has both arm7 and arm9 folders?

**Comment by Gericom** [comment]
From the root directory. It will then automatically build both the arm7 and arm9 and combine them into a nds file

**Comment by Cruplezone** [comment]
Alright I think that's everything and what's this 'nitrofiles' folder I may have to make?

**Comment by Gericom** [comment]
Git does not upload empty folders, so if it gives an error about a folder it can't find, just make it

**Comment by Cruplezone** [comment]
Came out with a red screen on top, white screen on bottom with the word "TAFN" on the top left on the bottom screen.

**Comment by Gericom** [comment]
It couldn't find a fat32 file system. Make sure your sd card is fat32 formatted

**Comment by Cruplezone** [comment]
Alright formatted and recopied, got the GBA bios intro to show up! After that white screened. If it's any help i'm trying to run emerald.

**Comment by Gericom** [comment]
Have you sram patched it with gbata? You need to do so if you haven't.

**Comment by Cruplezone** [comment]
Woop woop worked now haha thanks for helping me out through that I know this isn't supposed to be a forum place. Hopefully these instructions will help anyone else who comes by! 

Some comments now that I have it running: 1) audio feels slow. visuals run up to speed though but it may be just because i'm doing pokemon so it's not noticeable. 2) the game doesn't fit the screen, it's in the top left and the border colours around that square fill in the extra space so it looks odd

I know this is obviously still in development though so looks good so far thanks once again!

**Comment by Gericom** [comment]
Nice that it works now!

1. Still in development indeed
2. The gba has a smaller screen as the ds, and there are no resources left to mask out the border or center the picture. It would be possible by capturing the picture and using the sub screen, but that would introduce a 1 frame delay.
3. RTC cartridges are just not supported yet, but it should be possible to implement.

You don't have to create an issue for these issues, only if you find things that don't work as they should (graphics or gameplay wise)

**Comment by Cruplezone** [comment]
Hm how about not being able to move or do anything after exiting the moving truck in p. emerald, is that also related to it being RTC? Seems like it just won't take inputs but the music still plays. Weird

**Comment by Gericom** [comment]
Hmm, well, that might be related, but I'm not sure. These kind of issues are rather hard to debug, as it could be a lot of things that cause these things to happen, even down to timing race conditions.

**Comment by Cruplezone** [comment]
Ah I see well hopefully it gets looks into eventually, I can definitely see this going places. Until then my ds will be plugged in with a charger with a screen of my character forever waiting for his mom to open the front door so I can start playing the game haha. If it ever happens I'll let you know.

**Comment by Gericom** [comment]
Have you seriously kept your ds on? That is probably not very good for the screen...

Anyway, you might want to try the latest commit, it might fix some stuff

**Comment by Cruplezone** [comment]
Yeah haha I shut it off now though because you said to try the latest build. Don't worry it's not like it's an amoled panel or anything, but I won't do it again anyways just to be on the same side. BTW I made a script that pulls your code and devkit pro, compiles and cleans everything afterwards, all that you have to supply is a bios if you'd be interested I can send it to you to help out mac users. 

Gonna go test that new build now :)

**Comment by Gericom** [comment]
It's because the save is not saved to your sd yet. Sorry, I haven't implemented that yet.

**Comment by Cruplezone** [comment]
Yeah that's alright. That along with the textures would be the next step forward I would guess.
