### ISSUE TITLE
How does this black magic work?

### ISSUE THREAD

**Issue by artsyca** [Gericom/GBARunner2#100]
This is not an issue in the true sense I apologize --

I'm very interested to know how this wonderful apparatus works to run GBA games on my DSi LL

It's described as a `hypervisor` for DS which I guess is something like a virtual machine?
Does GBARunner2 work as an emulator in the traditional sense or is there some kind of compatibility layer built into the hardware?

In other words is there some vestigial GBA hardware in the DSi or are the processors operator-compatible with GBA code?

Incidentally in the case of a DS Lite and original DS is it true there is a physical GBA inside of those or is there some kind of emulation layer there as well?

**Comment by NightYoshi370** [comment]
This isn't really the place for questions like this. Please join the TWL Mode Hacking Discord. We could explain things there

**Comment by artsyca** [comment]
Linked at > https://github.com/DS-Homebrew/TWiLightMenu

Well appreciated
