### ISSUE TITLE
All games crash or freeze

### ISSUE THREAD

**Issue by Jalkhov** [Gericom/GBARunner2#102]
I have a **DSi XL Super Mario Bros 25th Anniversary**. I'm using **TWiLightMenu** (latest version) to run **GBARunner2** (latest version). All the games I tested freeze somewhere in the game or just don't start. Among them I tried:
**Mario & Luigi superstar saga**, it freezes when I choose Mario Bros from the main menu and in adventure mode when the first battle with Bowser is about to begin. The **Crash Bandicoot** just doesn't start and **Doom** has a lot of graphic deficiencies, and this last one is good, maybe it's because the project is still in development and some things need to be polished up but if that game runs, why not the others? I read something about disabling the main cache from the _TWiLightMenu configuration_, I already did it and nothing, rather the doom sticks even more, I will attach the structure of my sd card for what it's worth.
![Captura](https://user-images.githubusercontent.com/36505934/74094433-9bb4a800-4ab7-11ea-88d4-aa8031afcab1.PNG)
The way I run the _TWiLightMenu is accessing the camera_, then the sd card album and it redirects itself, I don't know if it has anything to do with it, I don't have a flashcard.

**Comment by RocketRobz** [comment]
Disabling main cache fixes the issue with the first battle.

**Comment by Jalkhov** [comment]
And will the rest of the game run normally? Another thing, is there a way to run the GBARunner2 without the TWiLightMenu?

**Comment by RocketRobz** [comment]
1. Maybe.
2. You can use the TWLMenu++ GUI to launch the ROM, instead of the GBARunner2 GUI.

**Comment by Jalkhov** [comment]
Well, to finish the subject, how would you do that last?

**Comment by RocketRobz** [comment]
Touch the DS icon on the bottom, then hide Quick Menu.
