### ISSUE TITLE
Tactics Ogre the Knight of Lodis - Doesn't Work

### ISSUE THREAD

**Issue by damikki** [Gericom/GBARunner2#105]
Hi,

My favourite game Tactics Ogre the Knight of Lodis on the Gameboy Advance doesn't run on GBARunner2.  It starts and shows the Gameboy Advance boot and then Shows the logo for Atlus and then it will go to a black screen. 

I am using a DSi with the latest TwilightMenu +, I have also tried downloading the lastest GBARunner directly from your github and manually copying it to the SDCARD but still no luck running the game.

Anyway thank you for your excellent software and your time. 

Kind Regards 

DaMikki

**Comment by zenseii** [comment]
This game is tested and working well on latest build f3daa51 on a 3DS.

**Comment by damikki** [comment]
I am glad this is fixed on the latest build on the 3DS, thank you for your hard work, however has anyone tested this on the DS or DSi before closing the issue ?

**Comment by damikki** [comment]
I have just tried the newest version on my DSi and it does not run Tactics Ogre as after the Atlus Logo the screen goes black and the console makes corrupt sound noises.  It does nothing else until a reboot.

**Comment by zenseii** [comment]
@damikki I tested it on this build on DSi https://github.com/Gericom/GBARunner2/releases/tag/v20200812-130512_d5dc8d8 and it now works and gets past the atlus logo. 

It currently does not run on the DS build.

**Comment by damikki** [comment]
> @damikki I tested it on this build on DSi https://github.com/Gericom/GBARunner2/releases/tag/v20200812-130512_d5dc8d8 and it now works and gets past the atlus logo.
> 
> It currently does not run on the DS build.

Hi zenseii,

Thank you for testing this, however despite running the latest TwilightMenu++ and the release you suggested above, I am still unable to progress beyond the title screen for Tactics Ogre the Knight of Lodis on a DSi.  The rom works on every emulator I run it on and on a GBA flash cart but will not run through GBARunner2 no matter which version I use.

Sorry 

Kind Regards 

DaMikki

**Comment by zenseii** [comment]
> > @damikki I tested it on this build on DSi https://github.com/Gericom/GBARunner2/releases/tag/v20200812-130512_d5dc8d8 and it now works and gets past the atlus logo.
> > It currently does not run on the DS build.
> 
> Hi zenseii,
> 
> Thank you for testing this, however despite running the latest TwilightMenu++ and the release you suggested above, I am still unable to progress beyond the title screen for Tactics Ogre the Knight of Lodis on a DSi. The rom works on every emulator I run it on and on a GBA flash cart but will not run through GBARunner2 no matter which version I use.
> 
> Sorry
> 
> Kind Regards
> 
> DaMikki
Hi,
Where are you copying the build to your SD card? Could you openany game and go to the gbarunner2 ingame settings (touch touch screen and press R) and go to 'about' and tell us the first 5 letters of 'Commit' and write what it says in 'Branch' and 'Version'?

I take it by SD card you mean the internal sd card of you DSi and not a flashcard's sd card? In other words do you have cfw on your DSi? Do you have unlaunch?

Also make sure to have both wram and main memory caches enabled in the settings.

**Comment by damikki** [comment]
> I take it by SD card you mean the internal sd card of you DSi and not a flashcard's sd card? In other words do you have cfw on your DSi? Do you have unlaunch?
> 
> Also make sure to have both wram and main memory caches enabled in the settings.

Hi zenseii,

Thank you for your quick response, I can indeed confirm that I am running the latest twilight menu and the build of GBA Runner you kindly mentioned above, on an internal micro SD card with custom firmware (unlaunch). I can confirm that I am not running on a flash cart.  I can also confirm that both wram and main memory caches are enabled in the settings. Would any other setting affect it ?

Thank you again for your help :)

Kind Regards 

DaMikki

**Comment by zenseii** [comment]
That's weird. Did you put the build I refered to above in root and run it through the file browser or did you put in in _nds? You should try it in root first if you didn't.

Also, if you can could you post the first 5 letters of 'Commit hash' and what it says in 'Version' when you use the build I sent above?

Other settings that would affect it are skip bios, which should be disabled. In other words don't skip it.

**Comment by damikki** [comment]
> That's weird. Did you put the build I refered to above in root and run it through the file browser or did you put in in _nds? You should try it in root first if you didn't.
> 
> Also, if you can could you post the first 5 letters of 'Commit hash' and what it says in 'Version' when you use the build I sent above?
> 
> Other settings that would affect it are skip bios, which should be disabled. In other words don't skip it.

Hi zenseii,

Firstly it is now working and I am very happy, thank you.  When you mentioned about commit hash it got me thinking that maybe I have a corrupt file in some way.  So I completely removed the installation and replaced it with a newly downloaded copy.  That completely fixed the issue :) Both from root of the sd card and via _nds, as I tried both and both are working fine now. 

before I go has anyone reported the text doubling issue on the Phantasy Star Collection, as that makes it impossible to read the text in episode 1 ?   

zenseii thank you very much for your help and support, greatly appreciated  :)

**Comment by zenseii** [comment]
> > That's weird. Did you put the build I refered to above in root and run it through the file browser or did you put in in _nds? You should try it in root first if you didn't.
> > Also, if you can could you post the first 5 letters of 'Commit hash' and what it says in 'Version' when you use the build I sent above?
> > Other settings that would affect it are skip bios, which should be disabled. In other words don't skip it.
> 
> Hi zenseii,
> 
> Firstly it is now working and I am very happy, thank you. When you mentioned about commit hash it got me thinking that maybe I have a corrupt file in some way. So I completely removed the installation and replaced it with a newly downloaded copy. That completely fixed the issue :) Both from root of the sd card and via _nds, as I tried both and both are working fine now.
> 
> before I go has anyone reported the text doubling issue on the Phantasy Star Collection, as that makes it impossible to read the text in episode 1 ?
> 
> zenseii thank you very much for your help and support, greatly appreciated :)

You are welcome! Note that since the build you are using is not merged with the DSP branch you might have some issues with regards to sound. I played until when you first get to the world map but I can't say whether there was something very wrong with audio since I don't know the game that well.

As for Phantasy Star that has indeed been reported. All roms have been tested and reported on the [compatibility list ](https://wiki.gbatemp.net/wiki/GBARunner2/DSi_3DS_Compatibility_List)quite recently on all systems, though not on the latest releases of the various branches.


Anyways I think you can close this issue now.

**Comment by damikki** [comment]
> > > That's weird. Did you put the build I refered to above in root and run it through the file browser or did you put in in _nds? You should try it in root first if you didn't.
> > > Also, if you can could you post the first 5 letters of 'Commit hash' and what it says in 'Version' when you use the build I sent above?
> > > Other settings that would affect it are skip bios, which should be disabled. In other words don't skip it.
> > 
> > 
> > Hi zenseii,
> > Firstly it is now working and I am very happy, thank you. When you mentioned about commit hash it got me thinking that maybe I have a corrupt file in some way. So I completely removed the installation and replaced it with a newly downloaded copy. That completely fixed the issue :) Both from root of the sd card and via _nds, as I tried both and both are working fine now.
> > before I go has anyone reported the text doubling issue on the Phantasy Star Collection, as that makes it impossible to read the text in episode 1 ?
> > zenseii thank you very much for your help and support, greatly appreciated :)
> 
> You are welcome! Note that since the build you are using is not merged with the DSP branch you might have some issues with regards to sound. I played until when you first get to the world map but I can't say whether there was something very wrong with audio since I don't know the game that well.
> 
> As for Phantasy Star that has indeed been reported. All roms have been tested and reported on the [compatibility list ](https://wiki.gbatemp.net/wiki/GBARunner2/DSi_3DS_Compatibility_List)quite recently on all systems, though not on the latest releases of the various branches.
> 
> Anyways I think you can close this issue now.

Very useful list thank you :)  I haven't played beyond starting a new game, I will test it out when I have a chance to play. 

Thank you again and I will now indeed close this.
