### ISSUE TITLE
Fast Forward Implementation for gbarunner2

### ISSUE THREAD

**Issue by Soccar** [Gericom/GBARunner2#110]
Is there any way possible for a fast forward function for gbarunner2?

**Comment by Gericom** [comment]
Nope, that is not really possible.

**Comment by Soccar** [comment]
Thanks! A question out of context. Do you know if i can make VC Injected games fast forward?

**Comment by Gericom** [comment]
That is definitely not possible, because they run basically on gba hardware.

**Comment by Soccar** [comment]
Thenks alot for your time!
