### ISSUE TITLE
Final Fantasy VI opening cutscene plays too fast.

### ISSUE THREAD

**Issue by Dartz150** [Gericom/GBARunner2#111]
The part where the robots walk through the snowy scenery with the intro credits plays faster than it should, but only the walking animations and the backgrounds seem to be affected.

The issue seems to happen because of the nature of that animation, it seems that the developers played that specific scene at half speed to save resources, because these are the same walking animations you see in game but slower. Maybe GBARunner misses some instructions in the way to play these at half speed or something.

Tested with the latest commit (c417fd0), .

**Comment by Dartz150** [comment]
Nevermind, just noticed that WRAM Cache causes this, so it should be kept dissabled for this game.

**Comment by Gericom** [comment]
Ah, good you found that out
