### ISSUE TITLE
Mario y Luigi super star saga

### ISSUE THREAD

**Issue by S-eba** [Gericom/GBARunner2#114]
Any way to play this game without disabling the "enable ds main memory i-cache" option, and what does it mean to disable it? Will my DSi XL die in the long term?

**Comment by RocketRobz** [comment]
Disabling that option just fixes some games.

GBARunner2 is a safe application that will not brick your DSi.

**Comment by S-eba** [comment]
Thank you very much bro, I was very nervous, since the dsi is the only thing I have xd, sorry for the time and greetings from Chile.
