### ISSUE TITLE
Sonic Advance 3 crashes in first level

### ISSUE THREAD

**Issue by MarioMover** [Gericom/GBARunner2#115]
The game seemingly runs fine, up until a single section in the first level. There's a little seesaw-type thing, where Sonic jumps on it and launches a weight in the air. Upon jumping on this little seesaw, the game - and effectively, the entire program - crashes immediately.

**Comment by zenseii** [comment]
I have played that without problems myself. Both on DSi and 3DS.

I would need some answers before I can actually help you. Which version are you playing on? DS,DSi, 3DS? Is your Rom clean or a romhack? What settings have you enabled in gbarunner2 menu? Are you using twilightmenu? What settings have you enabled in twilightmenu? Are you using the latest gbarunner2 from github?

**Comment by MarioMover** [comment]
DSi, latest versions of TWLMenu and GBARunner2. Settings are default, minus "play game on bottom screen". The ROM is clean, a No-Intro dump.

**Comment by zenseii** [comment]
Just finished the first level playing on a DSi using the latest build. I found the seesaw thing and the game did not crash. Try updating and see if it's fixed. 

This issue can probably be closed.
