### ISSUE TITLE
Stuck at logo when launching Pokemon Arcoiris

### ISSUE THREAD

**Issue by BjornGrylls** [Gericom/GBARunner2#119]
I can't launch the Pokemon Arcoiris game on my DSi running TWLmenu 14.0.0
When I have BIOS intro turned on, the game freezes at the end of the GBA logo animation.
When I have BIOS intro turned off, the game just shows a black screen after the blue GBArunner2 bar disappears. 
Neither ARM7 nor 9 works. Also tried turning off the other two settings that could interfear.

The game works fine with VisualBoyAdvance-1.8.0-beta3
I can play other GBA games including: Pokemon Ruby, Metroid Fusion, Pokemon Silver, Pokemon FireRed on the DSi

**Comment by RocketRobz** [comment]
The ROM probably uses hicode, which is why it doesn't work.

**Comment by zenseii** [comment]
It neither works on my DSi nor 3DS so yeah you're out of luck for this one at this moment.

**Comment by RocketRobz** [comment]
Also, please remove the download link, as it would contain copyrighted content.

**Comment by BjornGrylls** [comment]
Ok. Link removed.
I can't find an explanation on what hicode is. In the compatibility list, it just says hicode is the reason of crash. 

Could this release of GBArunner2 maybe help: 
github com/Gericom/GBARunner2/releases/tag/v20190914-122623_0131e15
