### ISSUE TITLE
Golden Sun title music garbled

### ISSUE THREAD

**Issue by twocows** [Gericom/GBARunner2#125]
The title music in Golden Sun is garbling at about ten seconds in (at about [this point](https://youtu.be/FVNkr6OAads?t=10)).

This is the US version of the game, CRC32 E1FB68E8. I am using the latest build of GBARunner2, but it also did it on the most recent release build (back from February I think). I'm on an old 3DS XL using the latest version of TWiLightMenu (also on up to date Luma and system software).

**Comment by zenseii** [comment]
Try turning wram i-cache off. You can possibly reenable it later.

**Comment by twocows** [comment]
That works. Still getting some popping noise (which I was also getting before), but the garbled audio is gone.
