### ISSUE TITLE
CIMA - the Enemy & Mario Golf - Advance Tour does not boot

### ISSUE THREAD

**Issue by mupp675** [Gericom/GBARunner2#130]
After the Gameboy logo they freeze with a white screen.

**Comment by zenseii** [comment]
What console are you using and what gbarunner2 version do you have? Tell me what date it says in the ingame menu accessed by touching the touch screen when a game is running and then pressing R and going to about. Have you checked the compatibility list:
DS:
https://wiki.gbatemp.net/wiki/GBARunner2
DSi/3DS:
https://wiki.gbatemp.net/wiki/GBARunner2/DSi_3DS_Compatibility_List

**Comment by mupp675** [comment]
Date  says 21-04-2020 and I'm using a DS light with a M3 card. The list they run fine with minor issues. Maybe I have bad ROMs?

**Comment by zenseii** [comment]
Yes, that would seem like the next possibility. If look at the compatibility list for the DS you'll find instructions on how to check if you have bad ROMS or not by comparing their hashes with the ones found on dat-o-matic.

**Comment by mupp675** [comment]
Ok, CIMA was bad and that's fixed now and is working, but Mario golfs MD5 was fine. I've tried both the US and EU version and they both crash at boot.

**Comment by zenseii** [comment]
Yes, as a matter of fact for Mario Golf on the compatibility list it is specifically stated that you have to use this build if you're using a base DS:
[https://github.com/Gericom/GBARunner2/releases/tag/v20190911-201047_371815e](https://github.com/Gericom/GBARunner2/releases/tag/v20190911-201047_371815e)

**Comment by mupp675** [comment]
O great, here I did everything to check if the ROM was right and I completely missed that line... Now it works but now I have to use different versions for different games? Why isn't this in the latest version?

**Comment by zenseii** [comment]
Some few games that are big require the ROM3M branch of gbarunner2 to run on the DS because of it having less RAM compared to the later systems. I am not sure why it isn't a part of the main branch however it serves no function for the DSi and 3DS builds so it wouldn't make sense to have its features come with their builds.

**Comment by mupp675** [comment]
No I guess not, but this is a regular DS so I want to make a suggestion that it should be in their builds. Thanks for the help.
