### ISSUE TITLE
Pal Park Pokemon

### ISSUE THREAD

**Issue by Canutox** [Gericom/GBARunner2#135]
Is there any chance or option to use Pal Park in 4th gen of pokemon? I mean using gbarunner2 and twilight menu++? Emulating like if a gba cartdrige is inserted in the console to transfer pokemon from emerald to diamond for example

**Comment by Gericom** [comment]
That would be a thing twilightmenu++ has to do on its own, because no emulation is needed for that. Iirc it would be enough to patch some ds sdk functions.
