### ISSUE TITLE
SpongeBob SquarePants - Revenge of the Flying Dutchman freezes after trademark screen

### ISSUE THREAD

**Issue by Poliwrath** [Gericom/GBARunner2#141]
```
  File: SpongeBob SquarePants - Revenge of the Flying Dutchman (USA, Europe).gba
  CRC-32: 30d6c979
     MD5: 0be6c13af62a0f75651bb2acbc397a56
   SHA-1: f5e28f897edb62019addcf3635ab89df032186a0
```

https://www.youtube.com/watch?v=BFr0US1vlEo
The game audio glitches + game freezes right when it's supposed to do the bubble screen transition (like the video above) to the nick logo.
Disabling warm i-cache makes the game work, but oddly the nick logo is just black for 2~ seconds and then goes to the THQ logo.

**Comment by zenseii** [comment]
> ```
>   File: SpongeBob SquarePants - Revenge of the Flying Dutchman (USA, Europe).gba
>   CRC-32: 30d6c979
>      MD5: 0be6c13af62a0f75651bb2acbc397a56
>    SHA-1: f5e28f897edb62019addcf3635ab89df032186a0
> ```
> 
> https://www.youtube.com/watch?v=BFr0US1vlEo
> The game audio glitches + game freezes right when it's supposed to do the bubble screen transition (like the video above) to the nick logo.
> Disabling warm i-cache makes the game work, but oddly the nick logo is just black for 2~ seconds and then goes to the THQ logo.

I thought that was a link to a vid of you showing your issue 😂

Anyways I need to know what system you are using? DS/DSi/3DS, flashcard or cfw. 

Have you checked your checksum hashes up against the https://datomatic.no-intro.org/  list of good dumps?

Have you checked the gbarunner2 compatibility list for your system and rom at this address?
https://wiki.gbatemp.net/wiki/GBARunner2

**Comment by Poliwrath** [comment]
DSi LL JP 1.4.5 + HiyaCFW, using whatever version of gbarunner2 + nds-bootstrap that came with twilight menu (I think latest?)
checksums are good
https://datomatic.no-intro.org/?page=show_record&s=23&n=0577
```

Format: | Default
-- | --
  | File: | 0577 - SpongeBob SquarePants - Revenge of the Flying Dutchman (USA, Europe).gba | 0577 - SpongeBob SquarePants - Revenge of the Flying Dutchman (USA, Europe).gba
0577 - SpongeBob SquarePants - Revenge of the Flying Dutchman (USA, Europe).gba
  | Size: | 8388608
  | CRC32: | 30D6C979
  | MD5: | 0BE6C13AF62A0F75651BB2ACBC397A56
  | SHA-1: | F5E28F897EDB62019ADDCF3635AB89DF032186A0
  | Serial: | AQ3E
```
Compatibility list has it as light green, ``SpongeBob SquarePants - Revenge of the Flying Dutchman [E]``

**Comment by zenseii** [comment]
@Poliwrath this ROM works fine at least since build of 04/21/2020 all systems as long as you disable wram icache. More recent builds possibly runs it better, but they all get past the logos.

This issue can be closed.
