### ISSUE TITLE
A way to reset settings

### ISSUE THREAD

**Issue by DeStilleGast** [Gericom/GBARunner2#143]
So I while back I was playing a old pokemon game and was playing with the settings (or something has changed) but the screen quality chase changed really bad, I was not able to make a screenshot or find the screenshot if I was able to make a screenshot.

I do use the TWIlight menu++, I did find a config ini file in _gba and deleted it, but that did not the trick it rememberd everything

**Comment by zenseii** [comment]
Weird... Which game? Deleting the ini resets all the relevant settings except for clock speed and vram boost (which should be off!) which is set in twilightmenu++, if you're on a dsi or 3ds. What console are you using? Are you getting this issue on other gba roms? 

What version of twilightmenu++ are you using?

**Comment by DeStilleGast** [comment]
it seems like it has effect on only 1 game (pokemon crystal clear (rom hack of pokemon crystal, you should give it a try))

TWI menu version: 15.3.0, updated it yesterday with nds-bootstrap: 0.35.1
new 2ds XL

it scales the game really bad

**Comment by DeStilleGast** [comment]
nvm, I'm on the wrong repo 🤦‍♂️
