### ISSUE TITLE
R4i(WOOD1.61) running error, Error messages: SCFG Locked!

### ISSUE THREAD

**Issue by QiuWeimengChan** [Gericom/GBARunner2#170]
My machine mode is New3DSLL with Luma10.2.1, But failed to run the GBARunner2 in NDS Mode, and I haved tried putting bios.bin on sdmc:/gba , sdmc:/ and sdmc:/_gba, however, I still can't run it successfully

**Comment by RocketRobz** [comment]
You need to run the regular DS build on your flashcard.

**Comment by QiuWeimengChan** [comment]
Thank @RocketRobz

**Comment by QiuWeimengChan** [comment]
Thank @RocketRobz , _arm9dldi_ds yes_ is running successfully, but _arm7dsi_dsi no_ and _arm7dldi_ds_ can't run too.
