### ISSUE TITLE
FAT16 support?

### ISSUE THREAD

**Issue by roytam1** [Gericom/GBARunner2#19]
I have a 2GB microSD for my old DSONE (the non-i version), which works best with FAT16 formatted.
but GBARunner2 can't read the card with FAT16.

**Comment by Gericom** [comment]
This should be fixed in eda125e70953b150a22db2e10cbbc31e68ccbad0

**Comment by TgamesFR** [comment]
@Gericom, not working for me.
I got a white screen (bottom Screen) with a black little box on the top corner left and a gray line at 1/3 of the screen. And also white screen at the upper screen.
SD 2GB Sandisk formated to FAT16 (32k cluster size) with SD Formater.

**Comment by TgamesFR** [comment]
I found the solution to make it works.
0) Backup every files of the SD Card
1) Use win32diskImager and read all bytes of the SD Card to a file
2) Use hxDwD and fill with 00 every hex values
3) Use win32diskImager and write all bytes from the file to the SD Card
4) Delete the primary partition under diskpart (cmd) or Computer Management
5) Launch again diskpart from the cmd
6) Type command :  List drive
7) Type command : select drive 3 (if the SD card is 3)
8) Type command : clean
9) Type command : create primary partition
10) Format the SD Card with Windows to FAT32 (Full erase) (NOT using a SD Tool => will not works with 2GB Sandisk Ultra 2)
11) Copy all backuped files back into the SD
12) Now GBARUNNER2 is no longuer display error or freeze !!!!!!

**Comment by Gericom** [comment]
Hmm, okay. I heard there were some issues with the arm7 version, which you use with twilightmenu, and I think I know the solution to that. But it seems you found another solution. After those issues are fixed, I would still be interested in trying if fat16 works though

**Comment by Gericom** [comment]
The latest commit of the sd_save branch has a fix for fat16. I hope it will fully work now
