### ISSUE TITLE
GBArunner 2 graphical glitch

### ISSUE THREAD

**Issue by EdwardSJ151** [Gericom/GBARunner2#199]
On my og3ds every game I play always has repeated pixels on the bottom part of the screen, and whenever you go to the GBArunner options, 2 more lines of pixels appear. 
![20210809_141028](https://user-images.githubusercontent.com/88259575/128759424-ff48056c-638a-4544-a575-f407a0093e23.jpg)
I already have borders active in the settings and closing my 3ds doesn't work either. After looking up everything I could online, nothing really worked. Pls help.

**Comment by zenseii** [comment]
Here's what you can do according to the official wiki:

https://wiki.gbatemp.net/wiki/GBARunner2/DSi_3DS_Compatibility_List#TWLBg_Bug_-_Duplication_of_lines_on_the_bottom_of_the_screen_when_playing_on_a_.28N.292DS.2F3DS

Strange that this doesn't show up earlier on searches.

**Comment by EdwardSJ151** [comment]
I really have no clue about homebrew and stuff, all I did was follow a YouTube tutorial on how to download twilight and some games. How would I install this "latest master release"?
![Screenshot_20210809-233058_Chrome](https://user-images.githubusercontent.com/88259575/128799400-299cc372-917c-4665-92f0-15f53f320bc0.jpg)

**Comment by zenseii** [comment]
You just put the right version for your system on your sd card somewhere and run it like you would with a rom through twilightmenu++

A lot more info can be found on the main page of the gbarunner2 wiki and I would suggest to read it for more tips and tricks:
https://wiki.gbatemp.net/wiki/GBARunner2
