### ISSUE TITLE
UNDFN IO Library error

### ISSUE THREAD

**Issue by patryckpo** [Gericom/GBARunner2#2]
I'm testing here and got this error for several games and they're showing the same code.
01007364
E3A00405
4000001F
0200A1D0

On a sidenote: This emu is only for DS and DS Lite? I'm testing on a DSi.

**Comment by Gericom** [comment]
Which games show this error? Also, it's interesting, because the address it crashes on is in my abort handler.

It should work on all systems DS, DS Lite, DSi and 3DS in DS(i) mode

**Comment by patryckpo** [comment]
All the games I tested until now unfortunately...
I can list if you want though.

**Comment by Gericom** [comment]
Did you try a game such as yoshi's island or mario kart super circuit? And have you sram patched if needed?

**Comment by patryckpo** [comment]
Wait a sec, I'll try here...

**Comment by patryckpo** [comment]
Tried here, but no luck.
I'll wait for now, because I can't patch those files (got no PC to test further), odd thing is all files do this same error. Anyways thanks for now.

**Comment by Gericom** [comment]
Mario Kart Super Circuit doesn't need patching. Maybe you're using a bad bios? Is the MD5 okay?

**Comment by patryckpo** [comment]
No BIOS. Begins loading on the red screen, with the bottom on white showing FIND and COPY, then after a while it brings a green screen overwriting the red, with the bottom in white again but showing the error. Gbaemu4ds runs fine here, even though it's an unnecessary information. MD5 is right, even gone an extra mile on getting another file but still not working.
Maybe the DSi I have isn't seeing something DS Lite would...(Model TWL-001eur)

**Comment by Gericom** [comment]
Strange, you must be doing something wrong...

**Comment by patryckpo** [comment]
Or even it's my flashcart or something (I have another but it's an outdated version of the one I'm testing now)...
Considering the BIOS doesn't boot, maybe it's my DSi that's not compatible.

**Comment by Gericom** [comment]
But you run it in ds mode, right? Then it should just work. It must be your card or something

**Comment by Cruplezone** [comment]
Ds lite dsi and 3ds all work for me

**Comment by patryckpo** [comment]
The flashcart is one that sold on r4-sdhc.com and it's the 2.10T version (use web.archive.org to get a pic of the cart)

**Comment by Cruplezone** [comment]
I have a r4i-sdhc I will test shortly

**Comment by Gericom** [comment]
@patryckpo You could try the read from arm9 branch (if you are not already using it).

**Comment by patryckpo** [comment]
I'm using the version on 2nd page of gbatemp thread of this project. When I get access to my PC again I'll try some more. Thanks

**Comment by Cruplezone** [comment]
Can confirm it is an issue with the flashcard, not the system. 

I'm getting a "UNDF DLDI(boyakkey ver.)" green top screen after find and copy with sdhc flashcard on all devices... which sucks because my acekard runes it fine but is not compatible with the 3ds or dsi. Anyways he probably mentioned it before but here are the codes under:

01007364
E3A00405
4000001F
0200A1D0

**Comment by Gericom** [comment]
LAST means it couldn't find the file (either bios.bin or runner.gba).

**Comment by Cruplezone** [comment]
Everything is on the root of the microSD guaranteed.

**Comment by Gericom** [comment]
The new branch works fine for me on an original r4 with wood firmware

**Comment by Cruplezone** [comment]
Well then it was fun while it lasted

**Comment by Gericom** [comment]
I don't understand why it wouldn't work. It's correctly using DLDI

**Comment by Cruplezone** [comment]
Beats me. In summary:

1) Master build works on my acekard
2) Master build results in green screen with "UNDF DLDI(boyakkey ver.)" after find, copy screens with following error codes:
01007364
E3A00405
4000001F
0200A1D0
3) arm9 speed read build results in LAST on both acekard and r4i-sdhc

Maybe the error codes from the master green screen can provide info?

**Comment by Gericom** [comment]
"01007364
E3A00405
4000001F
0200A1D0"
Looking at this it shouldn't even have a reason to call the undefined handler

**Comment by patryckpo** [comment]
Wow, so I have to get an Acekard... no worries, hope you can fix it, when you need to, you can close this issue as it is per-device bug (good to know acekard runs fine). Thanks for clarification @Cruplezone
On a sidenote: Gbaemu4ds shows the cart uses "DEMON IO Library", maybe this can help solve the problem.

**Comment by cotodevel** [comment]
I had the same issue with ARM9 branch. Couldnt get it to work. Anyway: I'll speak for master branch only, But if the dldi has not ARM code @ io_dldi + 8 But garbage is expected to prefetch / undefined abort to happens (invalid dldi). So to my eyes, master branch is OK. ARM9 branch will require further testing

**Comment by Gericom** [comment]
Are there dldi drivers that don't have an init function for example? That might give a problem. But for the LAST, it means that it was actually able to read from the sd, but couldn't find the file for whatever reason. Would be interesting to see why that happens

**Comment by cotodevel** [comment]
I have the feeling both dldi will work just fine with any normal dldi nds homebrew, but the dldi header on r4i-SDHC is altered/scattered on purpose ("DEMON IO Library" vs "UNDF DLDI(boyakkey ver.)".

"LAST DLDI(boyakkey ver.)" is invalid since "LAST" vram part is written by one of the debug opcodes gericom had there while booting gbarunner2.

-

So what both 
@Cruplezone @patryckpo  could do: run http://www.mediafire.com/file/zzi8krg0oeqkhc0/dldiextract.nds from your carts. (from the carts that prevent master branch gbarunner2 to boot). This extract your dldi to sd card. 

1)You could post them here

2) download also http://www.mediafire.com/file/tcdj9w2pht9rveo/dldipatcher.zip

3)install moonshell2, dldipatch (move your extracted dldi to dldi folder of dldipatcher)

4) run dlditool32, choose your "DEMON IO Library" dldi, I doubt the "UNDF DLDI(boyakkey ver.)" will apear. And patch moonshell2 (whatever version 2.10 will do). Also backup your r4i-SDHC sd card

5) format: FAT32, 32K cluster size your SD cards, put back all kernel stuff

6) run moonshell2, and run from there gbarunner2 (the master branch) as the steps gericom said

**Comment by Cruplezone** [comment]
Will do give me 5 minutes

**Comment by cotodevel** [comment]
1) 
moonshell2 2.10: download: http://www.mediafire.com/file/o2pjpxkovfwh8v3/201002161705_moonshell210stable.exe (safe .exe, its just the embedded installer)
and install (connect r4i-SDHC sd card, choose drive letter)

2)
dldipatcher.zip > decompress

open dldipatcher folder

open dldi folder

<copy your extracted dldi here>

run dlditool32.exe, choose moonshel2 (moonshl2.nds that just got installed), dldi patch .

open mshl2.nds from r4i-SDHC, run gbarunner2 master branch and see if the same happens

**Comment by Cruplezone** [comment]
Alright thanks @cotodevel I succesfully patched moonshel2.nds. I did not patch moonshl2_Altloader or moonshl2_DirectBoot. I also did not dldi patch gbarunner2. 

Ran moonshel on my cart, booted fine and ran gbarunner2, still got LAST DLDI(boyakkey ver.)

**Comment by cotodevel** [comment]
ok, thank you for the tests. Finally I have tested 


97223ad (master branch) is working fine. (the last good one)

78945c3 (master branch) UNDF green screen undefined exception 

DSTTi , r4igold.cc here.

**Comment by Cruplezone** [comment]
[GBARunnerBuildScript-Cruplezone.txt](https://github.com/Gericom/GBARunner2/files/665430/GBARunnerBuildScript-Cruplezone.txt)

There I got so sick of building it I made a script for everyone on mac/linux have fun. 

And yes I can confirm with @cotodevel on the SDHC card 97223ad works great, @Gericom afraid something broke in the reading bin from the sd card commit. 

Game runs and shows: DSTT DLDI(boyakkey ver.) on bottom screen.

**Comment by Gericom** [comment]
Hmm, I'll have a look at it. Could you guys try fat32 with 4 kb clusers? Maybe reading 32k at once overwrites something (shouldn't).

**Comment by Gericom** [comment]
Oh, I could also try to make a sub branch that includes the bios in the rom again, but still reads from arm 9

**Comment by Cruplezone** [comment]
@Gericom 4kb clusters sped the rom speed right on par with my other card!

**Comment by Gericom** [comment]
Nice! It's because when it needs to read one 32 bit value for example it would have to read 32 kb. There's probably some cluster size that's perfect. You could try to find the sweet spot

**Comment by Gericom** [comment]
And could you try 4 kb clusers with the arm 9 branch too?

**Comment by Cruplezone** [comment]
Yeah no problem so far I have
1) External bios build runs at full speed now
2) Latest master with external bios now works (no more green screen)

**Comment by Gericom** [comment]
The 32k clusters are giving problems with bios loading currently, because I'm copying whole clusters and the bios is 16k.

I'll have to do further research into the LAST problem

**Comment by cotodevel** [comment]
I got Undefined exception when mis aligned read / writes also in gbaemu4ds. Perhaps LAST is being up ALTS or ATSL .. the offseting for halfword single load stores is picky.

**Comment by cotodevel** [comment]
I meant that for bios.bin search pattern ;) my mistake

**Comment by Gericom** [comment]
LAST is fine. It's the error code I put there. Just like UNDF. Mis aligned reads shouldn't invoke undefined exception and also shouldn't happen in my sd code anyway.

**Comment by Gericom** [comment]
What do you mean

**Comment by cotodevel** [comment]
Basically you hardcode the sector offset by 512 (fat?), But ARM byte swap halfword reads at odd offset (truncated as halfword). That is misalign and that mean exception.

**Comment by cotodevel** [comment]
Which would explain why is not finding your hardcoded filenames. Thats what I mean.

**Comment by Gericom** [comment]
I don't know if you saw I'm using READ_U16_SAFE, which can read from unaligned addresses

**Comment by cotodevel** [comment]
But I mean from reads to write to vram. Are you sure vram is not swapping your fetched sectors.

**Comment by Gericom** [comment]
I don't think so, because it was able to detect the boot sector and fat32 file system. As I said I'll make some stuff to debug this. I'm sure we'll be able to fix this

**Comment by cotodevel** [comment]
Another stuff: vram @ arm7 can do single multiple load stores 8 16 and 32 bit . Vram@ arm9 can only 16 and 32 . What if _DLDI_readSectors_ptr is storing sector data wrongfully truncating to 16 bits.

**Comment by Gericom** [comment]
I know this, but as I said before. If it wouldn't be able to read the sd card right, it would have given another error.

**Comment by Gericom** [comment]
Run this and see which files it shows (shows 23 files max! because the screen isn't bigger xD)
[GBARunner2.zip](https://github.com/Gericom/GBARunner2/files/666260/GBARunner2.zip)

**Comment by Cruplezone** [comment]
Sorry for the wait went to sleep. Just we're clear what I'm testing at this point this is (r4i-sdhc YSMENU 4kb Clusters Fat32):

Debug ran the rom fine actually. Is it a debug of the arm9 read branch or master...? arm9 read branch alone still does not load the rom. Here are the files it found:
SYSTEM~1
GBARUN~1
TTMENU
BIOS

**Comment by Gericom** [comment]
It's the arm 9 debug branch. Which is a sub branch of the arm 9 branch. So if the debug works, the non debug should work too actually.

**Comment by Cruplezone** [comment]
Can you send me a compiled arm9 branch maybe I'm not compiling it right or something...

**Comment by Gericom** [comment]
I can't do that right now. I'll post it here tomorrow. Maybe different versions of devkitarm could yield different results. Would be strange though.

**Comment by Cruplezone** [comment]
Oh I didn't see you uploaded the debug branch okay I'll try building both the debug and the arm9 branches myself and then test to see if it something due to that because the .zip you uploaded works fine.

**Comment by Gericom** [comment]
I've a bit older version of it. You could try a couple of versions

**Comment by Cruplezone** [comment]
[LASTBuilds.zip](https://github.com/Gericom/GBARunner2/files/667201/LASTBuilds.zip)

There you are.

**Comment by Gericom** [comment]
@Cruplezone Could you upload the arm9 elf file instead. It's hard to compare, because nds roms do not contain symbols of course.

**Comment by Cruplezone** [comment]
@Gericom Hopefully these are correct?
[arm9_ELFS.zip](https://github.com/Gericom/GBARunner2/files/670355/arm9_ELFS.zip)

**Comment by Gericom** [comment]
@Cruplezone You know what the problem is? For some reason the newer version of devkitarm will translate this:
`	for(int i = 0; i < sizeof(vram_cd->cluster_cache) / 4; i++)
	{
		((uint32_t*)&vram_cd->cluster_cache)[i] = 0;
	}
	for(int i = 0; i < sizeof(vram_cd->gba_rom_is_cluster_cached_table) / 4; i++)
	{
		((uint32_t*)&vram_cd->gba_rom_is_cluster_cached_table)[i] = 0xFFFFFFFF;
	}
	for(int i = 0; i < sizeof(vram_cd->cluster_cache_info) / 4; i++)
	{
		((uint32_t*)&vram_cd->cluster_cache_info)[i] = 0;
	}`
into 3 memset calls. But of course, memset is not available, and that's the reason I was using these loops. In fact, I commented out these 3 lines that were there previously:
`
	//memset(&vram_cd->cluster_cache, 0, sizeof(vram_cd->cluster_cache));
	//memset(&vram_cd->gba_rom_is_cluster_cached_table, 0xFF, sizeof(vram_cd->gba_rom_is_cluster_cached_table));
	//memset(&vram_cd->cluster_cache_info, 0, sizeof(vram_cd->cluster_cache_info));
`
-ftree-loop-distribute-patterns is added in the new version of the compiler to the O3 options, so that's the reason. Could you try using O2 instead and see if it works?

**Comment by Cruplezone** [comment]
Tried the latest O2 patch still no go
[GBARunner2-sound_improve.elf.zip](https://github.com/Gericom/GBARunner2/files/671625/GBARunner2-sound_improve.elf.zip)

**Comment by Gericom** [comment]
@Cruplezone The calls to memset are gone now, but for some reason your build ignores my MI_WriteByte function, and emits an **STRB** instruction instead! This doesn't work, because we're in vram. It will be ignored! I think I'll have to add the 
```__attribute__ ((noinline))``` to that function. Could you try if that does the trick for you?

**Comment by Cruplezone** [comment]
okay so I think I can get quick tests for you now. Also just tested and it works great, amazing work :) I think it's safe to say this issue can now be closed! Thanks once again @Gericom this is no lie the project I'm most hyped for atm. just awaiting that save functionality, rts, and most importantly for me some kind of solution to the video scaling issue! Happy holidays @Gericom thank you!

**Comment by Gericom** [comment]
Thanks a lot! Nice that this is resolved. Did you see that I added masking and centering in the latest commit on sound improve. You have to uncomment a define, since it's still experimental.

**Comment by Cruplezone** [comment]
@Gericom no I did not notice haha thanks for pointing it out! But trying it on my 3ds it does not look so good... the screen is pretty glitchy, not properly cropped, and the top actually appears on the bottom instead of the top (like it loops vertically and is cut off). Basically the overall picture looks pretty bad, worse than it normally does because of the looping, which I guess is expected from it being experimental! Do I even both making an issue on this at this point? Haha great work once again though glad you're implementing it although you said you had lack of resources before. How'd you get around that I wonder...?

**Comment by Gericom** [comment]
It appearently doesn't work on a 3ds. Only on ds and dsi. Must be some hardware difference

**Comment by mariogamer2** [comment]
@Gericom Is there a workaround?

**Comment by Gericom** [comment]
I don't know, I also found out that there were some problems on a ds too. Apparently affine bgs don't shift correctly. VBlank line 263 (vcount 262), which is the last one, seems to reset the lcd to start drawing from the top again, so it needs to appear at the right physical line in order to work correctly, but I think it initializes the affine counters too, shifting them.

**Comment by Cruplezone** [comment]
Seeing as soundhax and mgba is out for the 3ds now, I don't see this project NEEDING to be compatible with the 3ds, although it would be cool.

**Comment by mariogamer2** [comment]
@Cruplezone mgba is an **emulator**,and it's laggy. This is native support for gba,so it would be very good to have 3ds compatibility....

**Comment by Cruplezone** [comment]
@mariogamer2  mgba (non-libreto/retroarch) runs every rom 100% on n3ds that i've tried. what game are you having issues with, is it because you have o3ds (if so you should upgrade). although yes native support would be a cool project.

**Comment by Gericom** [comment]
The 3DS has AGB_FIRM anyway, which IS native gba support.

**Comment by Cruplezone** [comment]
@Gericom true, I recommend you focus mainly on ds and dsi for now as I'm sure anyone on 3ds has gba running by now just fine. then fix the 3ds bugs after :) (although I will be eagerly waiting, mgba does not have fullscreen support or at least i cannot find it)

**Comment by Gericom** [comment]
I don't have a 3ds myself, so I wouldn't be able to test it anyway. Also it's not my fault that the nds bootstrap dldi needs this irq handler patch, because the sd is only accessible from arm 7. And there are dldi problems with some flashcards too (acekard 2i for example).

**Comment by mariogamer2** [comment]
I know,the problem is that there's most likely no tool for gba2ciaing on linux :(.

**Comment by Gericom** [comment]
Would probably be not very hard to port, and you could probably use wine, a vm or just windows anyway
