### ISSUE TITLE
can't compile.

### ISSUE THREAD

**Issue by 3EGaming** [Gericom/GBARunner2#20]
I cant compile GBARunner2 because I dont have any devkitpro compatable computers at the moment. could you send me a compiled rom.

thanks in advance.

**Comment by piratesephiroth** [comment]
here's a build of the latest commit
[GBARunner2.zip](https://github.com/Gericom/GBARunner2/files/1747566/GBARunner2.zip)

**Comment by FlameKat53** [comment]
Binaries are now provided for every commit on each branch, this should be able to be closed now.

**Comment by 3EGaming** [comment]
Sorry I kept it open so long I forgot all about this
