### ISSUE TITLE
[Feature Request] Automatic SRAM Patching, or Patching Tool

### ISSUE THREAD

**Issue by aphirst** [Gericom/GBARunner2#21]
I'm not sure whether or not this is "in scope" for GBARunner2.

If it is, it would be very convenient, since running GBATA means Windows or WINE in Linux / Darwin on OSX (I'm sure GBATA works well there, but the dependency is potentially... "excessive"), in order to get SRAM saving to work. To the best of my knowledge, there is no Linux/OSX native equivalent tool. (But if there is, please feel free to lay my ignorance bare!) I'm fairly certain lots of DS/GBA flashcards (e.g. using the EZFlash 3-in-1) would do this.

If not, I think it's probably still best to have asked, and have the ticket here for posterity; but I'd also be curious as to what the suggested next course of action should be - short of resignation and using Windows/Wine, I mean.

**Comment by Gericom** [comment]
Eventually I would like to support all types of saves natively, since sram patching does break some games.
