### ISSUE TITLE
[Feature] Saving to SD

### ISSUE THREAD

**Issue by Gericom** [Gericom/GBARunner2#22]
#### States
<ol start="0">
  <li>Save Clean</li>
  <li>Save Dirty</li>
  <li>Save Delay Started</li>
  <li>Save to SD Requested</li>
</ol>

#### Description
First the fat table of the save file would be stored in an array. Then a variable is set to **0**, which means **save clean**. Whenever the game writes to the save, this value is set to **1**, **dirty**. On arm7 a timer will issue an irq every 250-500ms. If it sees a **0**, nothing happens. If it sees a **1**, it will change it in **2** (**save pending**). While it's **2**, the game might still save, setting it back to **1**. When it's done, the irq will see **2**. It will send a request to the arm9 to save to sd and set the value to **3**. On arm9 saving is then handled (from the irq handler) and the value is set back to **0**.

![image](https://user-images.githubusercontent.com/5251038/41778298-9b9df7a4-762e-11e8-9f29-74fb58793621.png)

### Implementation Details
To be implemented in the following order:
- [x] **_Shared_** - Add variables: Save status, save enabled, save fat table, sector tmp block
- [x] **_ARM9_** - Use sector tmp block 
- [x] **_ARM7_** - Save timer + irq About 250-500 ms
- [x] **_ARM9_** - Save status update on write
- [x] **_ARM9_** - Irq handler extension for saving
- [x] **_ARM9_** - Save to SD C++ code
- [x] **_ARM7_** - Write SD command for arm7 dldi

**Comment by yoyoliyang** [comment]
amazing! but metroid fusion still no sound play.

**Comment by HippoZhao** [comment]
cool! expected that this feature can be implemented earlier

**Comment by Gericom** [comment]
@yoyoliyang Wasn't that fixed on the file_explorer branch? Note that it doesn't build correctly with the latest version of devkitarm.

**Comment by yoyoliyang** [comment]
I use the lastest build binary from the gbatemp.net forum wiki page.(Commit 83108c7 (2018/03/04) (arm9 Version)).
I think this software is fantastic because I can't go buy flashcart like ezflash or other.

**Comment by Gericom** [comment]
@yoyoliyang Metroid sound was fixed in 5986d71 actually. It was not merged into master yet though.

**Comment by yoyoliyang** [comment]
@Gericom I use the file_explorer branch code and build wiht devkitarm, with "make" command, i get this .make[1]: Leaving directory '/home/yang/GBARunner2/arm9'
ndstool -c GBARunner2.nds -7 arm7/GBARunner2.elf -9 arm9/GBARunner2.elf
Nintendo DS rom tool 2.1.2 - Jun 13 2018
by Rafael Vuijk, Dave Murphy, Alexei Karpenko
but when i run the GBARunner2.nds on my ndsi,with the YSmenu kernel,I got the white screen, on the bottom screen, i got the "BINF DLDI(boyakkey ver.)". stuck in the white screen.
so, what's wrong with this?

**Comment by Gericom** [comment]
@yoyoliyang It means bios.bin could not be found. I'm not sure if it will work at all with the latest devkitpro.
[GBARunner2.nds.zip](https://github.com/Gericom/GBARunner2/files/2140545/GBARunner2.nds.zip)
This one should work I guess.
We should stop discussing this here though. This is really off-topic.

**Comment by yoyoliyang** [comment]
@Gericom IT WORKS! but I put the bios.bin in the root path of the sdcard.
I will stop discussing this in here.
thank you very much!

**Comment by Gericom** [comment]
Saving to sd was implemented in f89fac5
