### ISSUE TITLE
Bios Intro Error

### ISSUE THREAD

**Issue by flabberjack** [Gericom/GBARunner2#23]
I am having issues with both Pokemon Sapphire (E) and Pokemon Ruby (E). The screen goes white after the bios intro and I looked on other threads and you said that games that had this error were uncompatible. I double checked on the compatibility list and sure enough these games should be compatible. I tried all the different versions of GBArunner2, specifically the arm7 and arm9 versions including the wramicac versions. Looking for some answers. Thanks in advanced!

**Comment by Gericom** [comment]
Have you checked in an emulator on pc that those games don't contain a release scene intro or something? And if that's not the case, did you sram patch them?

**Comment by flabberjack** [comment]
I did srm patch and removed the intro on both of them just incase. I'm using DSI menu++. I'm new to this whole scene lol.

**Comment by Gericom** [comment]
So you removed the intro, sram patched and tested if it still worked in an emulator afterwards? And it still didn't work?

**Comment by flabberjack** [comment]
Okay here are my findings on the DSI. I repatched everything for both roms.

1) SRAM and Intro patch results in the game loading into the 1996 game freak screen and then proceeds to not load after that.

2) Just SRAM results in the same outcome as #1

3)Just intro patch results in whitescreen after bios intro.

All the roms worked no matter what I did to them on a PC emulator.

**Comment by Gericom** [comment]
You could try to make a save on pc and use it with gbarunner2 with the rom from situation 1

**Comment by flabberjack** [comment]
no luck :(

**Comment by Gericom** [comment]
Which version (commit id) did you use. The wiki says it was tested with 091719f wramicache. Maybe you should try that version.

**Comment by flabberjack** [comment]
I tried all 4 and I get a whitescreen after I try to run it.

**Comment by Gericom** [comment]
Hmm, idk then. I'll give them a try some time. But as you probably know I'm currently not really active, because of physical problems

**Comment by flabberjack** [comment]
Thanks for the help though. Take your time and get better! I'll see what I can do on my own.

**Comment by Gericom** [comment]
Thanks! My therapist wants me to start doing some things little by little again. I started doing some save stuff, so I'm doing my best. Maybe I can get it to a working state later this week.

Maybe you can try a different region rom or something.

**Comment by Valkristh** [comment]
Hello! 
Flabberjack try to run gbarunner2 from dsimenu++ as a nds like other game, it's worked for me in some games.

Gericom thank you for this update and goodluck with your therapy

**Comment by tydowntyty** [comment]
Hey flabberjack. I have you tried Pokemon Ruby (U) v1.1? That one works for me. I also have Firered (U) v1.1 working. So try a v1.1 version.

**Comment by malek78i** [comment]
@tydowntyty

Do you SRAM Patched the v1.1 game? I have them too but they don't work for me (Pokemon Ruby v1.1)
