### ISSUE TITLE
Big Mutha Truckers Saving just be a regression started before the game starts with Commit 6522414 (2018/11/01)

### ISSUE THREAD

**Issue by qamichele59** [Gericom/GBARunner2#232]
Since I am no longer coding/maintaining gbaemu4ds I wanted to share some tips I have found while at it and I am sure those will be of help to GBARunner2 project.

1#)
GBARunner2: Since 2018 or so I was never able to run Big Mutha Truckers (U) again. So I decided to build a "custom" GBARunner2 version having all the latest improvements + my own. But I found the game working fine between 2018 - 2021 here :).

Turns out a certain commit tried it work fine

8e4d520 -> Saving works perfect.

6522414 -> Sometimes can be saved results to play well. Don't know if you try to save the game.

Current Environment I have: devkitARM r45 and the same libnds and libfat GBATemp user mentioned here: https://gbatemp.net/threads/gbarunner2.451970/page-75#post-8672889

Also when I added stuff to gbaemu4ds, I found other games to play often when VRAM or IO read / writes were unhandled / omitted or deadlocks when certain load/store memory operations would leave bus conflicts unresolved between different memory such as the VRAM and the EWRAM (at ARM9).

**Comment by qamichele59** [comment]
#52

**Comment by newestdodain47** [comment]
Reported that is Commit 6522414 (2018/11/01) arm9 version? How about to save the game that fixed with Commit 8e4d520 (2019/06/14) arm9 version as well sometimes?
