### ISSUE TITLE
Gradius Galaxies still doesn't save on GBAR2??

### ISSUE THREAD

**Issue by qamichele59** [Gericom/GBARunner2#235]
it recommends boot the game, but still keeps asking you to delete one of the saved files and it does not even continue due to freezes so any to fix for this? They all work on VisualBoy Advance-M Emulator.

**Comment by newestdodain47** [comment]
It's impossibly caused me a preliminary saving issue from the Gradius Galaxies? Now still testing this one on PC using mGBA with Keyboard controller.
