### ISSUE TITLE
GBARunner is broken

### ISSUE THREAD

**Issue by F3arM3** [Gericom/GBARunner2#247]
I have only tested 2 games so far but circle of the moon has severe audio lag and megaman zero has background screen tearing and severe slowdown when the flashcard was ina ds lite, and when inserted in a 3ds the bottom 5th on both screens are made up of  5 repeating rows in every gba game, but the cotm audio lag is gone, I just updated to the latest version of twilight menu

**Comment by F3arM3** [comment]
testing my collection in my ds lite I found
Metroid fusion (US+JP), alien hominid, Nes Classic Series Metroid, and Wario land 4 only boot to a grey screen
Densetsu no stafy2 has audio warping 
Densetsu no stafy 3, and famicom mini series metroid crash the system 
chain of memories has screen tearing and audio crackling in fmv's
lego star wars has severe slowdown on the title screen
puyo pop stutters when loading the title screen and mode select has no text
Sega smash pack crashes the system after the licensed by nintendo screen
Series of unfortunate events has spikes of slowdown when moving quickly
sonic advance 1&2 seem to trigger some kind of anti piracy lockout

**Comment by michele559** [comment]
Now all working on mGBA3DS, but not GBARunner2. Some Games like Driver 3 (USA) and Stuntman and V-Rally 3 has been caused by a corrupted transfer from WRAM through HEX Address that has a size: 0x034BFFF0. Clamping size prevents amd fixes the crash after Atari logo in mGBA3DS Emulator as well, sometimes it plays very slow on a Old 2DS so enough.....;)

**Comment by michele559** [comment]
> testing my collection in my ds lite I found Metroid fusion (US+JP), alien hominid, Nes Classic Series Metroid, and Wario land 4 only boot to a grey screen Densetsu no stafy2 has audio warping Densetsu no stafy 3, and famicom mini series metroid crash the system chain of memories has screen tearing and audio crackling in fmv's lego star wars has severe slowdown on the title screen puyo pop stutters when loading the title screen and mode select has no text Sega smash pack crashes the system after the licensed by nintendo screen Series of unfortunate events has spikes of slowdown when moving quickly sonic advance 1&2 seem to trigger some kind of anti piracy lockout

Some Classic NES Games are has been caused by a corrupted transfer from WRAM through HEX Header Address that has a size: 0x01300000. Clamping size fixes the crash after bypassing the AP Protection in mGBA3DS Emulator.

**Comment by michele559** [comment]
Reported from the Original PS2 Game issues like it is "Open-PS2-Loader/issues/590" so you can play the game on a OPL Beta 1.1.0 emulation and it Working Here OK!

**Comment by michele559** [comment]
Before you can check from the GBARunner2 Issues like it is "Gericom/GBARunner2/issues/247" without it after loading the game, the game will can be tested only with SLES-51503 ISO?

**Comment by michele559** [comment]
This game has some issues like it is "niuus/WiiSXRX/issues/54" here.

**Comment by michele559** [comment]
This game has some issues like it is "libretro/pcsx_rearmed/issues/591" here.

**Comment by Epicpkmn11** [comment]
> I have only tested 2 games so far but circle of the moon has severe audio lag and megaman zero has background screen tearing and severe slowdown when the flashcard was ina ds lite, and when inserted in a 3ds the bottom 5th on both screens are made up of 5 repeating rows in every gba game, but the cotm audio lag is gone, I just updated to the latest version of twilight menu

Audio issues are a known issue on DS Lite, it's better on DSi with Unlaunch/3DS since they can use the DSP processor for that.

The graphical issues with repeating lines are a bug in TWL_FIRM made worse by GBARunner2 messing with the frame rate in DSP builds, honestly the best solution is to just use VC Injects, open_agb_firm, or (only on n3DS) mGBA, GBARunner2 just isn't that great on 3DS as it's intended for DS/DSi.

The Sonic Advance issue isn't AP but rather it checking for the link cable, it works in Wi-Fi link builds, but for main builds you'll just need to patch the ROMs with the patch in [the compatibility list](https://wiki.gbatemp.net/wiki/GBARunner2/DSi_3DS_Compatibility_List), not sure about the rest of your issues though using a [proper BIOS dump](https://wiki.ds-homebrew.com/gbarunner2/bios) may help if you're not.

---

@michele559 can you at least keep your off topic spam to your own issues, if you legitimately want help/to help at least listen to what people say to you.

**Comment by michele559** [comment]
> > I have only tested 2 games so far but circle of the moon has severe audio lag and megaman zero has background screen tearing and severe slowdown when the flashcard was ina ds lite, and when inserted in a 3ds the bottom 5th on both screens are made up of 5 repeating rows in every gba game, but the cotm audio lag is gone, I just updated to the latest version of twilight menu
> 
> Audio issues are a known issue on DS Lite, it's better on DSi with Unlaunch/3DS since they can use the DSP processor for that.
> 
> The graphical issues with repeating lines are a bug in TWL_FIRM made worse by GBARunner2 messing with the frame rate in DSP builds, honestly the best solution is to just use VC Injects, open_agb_firm, or (only on n3DS) mGBA, GBARunner2 just isn't that great on 3DS as it's intended for DS/DSi.
> 
> The Sonic Advance issue isn't AP but rather it checking for the link cable, it works in Wi-Fi link builds, but for main builds you'll just need to patch the ROMs with the patch in [the compatibility list](https://wiki.gbatemp.net/wiki/GBARunner2/DSi_3DS_Compatibility_List), not sure about the rest of your issues though using a [proper BIOS dump](https://wiki.ds-homebrew.com/gbarunner2/bios) may help if you're not.
> 
> @michele559 can you at least keep your off topic spam to your own issues, if you legitimately want help/to help at least listen to what people say to you.

Now still playing the Whole PSX Version of Driver 2 (Disc 1) & (Disc 2) game on a PCSX-ReARMed libretro3DS core emulator as well without it after trying to access the memory card on the save datas menu screen.

**Comment by michele559** [comment]
Futari ha Precure Arienaai Yume no Kuni ha Daimeikyuu has been crashing on the previous GBARunner2 builds, but has "data abort" errors and still doesn't work on the latest mGBA3DS builds.....;(
Futari wa Precure Max Heart Maji! Maji! Fight de IN Janai has been crashing on the previous GBARunner2 builds, but has "prefetch abort (kernel panic)" errors and still doesn't work on the latest mGBA3DS builds.....;(
Sugar Sugar Une - Heart Gaippai! Moegi Gakuen has been crashing on the previous GBARunner2 builds, but has "prefetch abort (svcBreak)" errors and still doesn't work on the latest mGBA3DS builds.....;(
Dai-Mahjong has been crashing on the previous GBARunner2 builds, but has "undefined instruction" errors and still doesn't work on the latest mGBA3DS builds.....;(

**Comment by qamichele594** [comment]
> testing my collection in my ds lite I found Metroid fusion (US+JP), alien hominid, Nes Classic Series Metroid, and Wario land 4 only boot to a grey screen Densetsu no stafy2 has audio warping Densetsu no stafy 3, and famicom mini series metroid crash the system chain of memories has screen tearing and audio crackling in fmv's lego star wars has severe slowdown on the title screen puyo pop stutters when loading the title screen and mode select has no text Sega smash pack crashes the system after the licensed by nintendo screen Series of unfortunate events has spikes of slowdown when moving quickly sonic advance 1&2 seem to trigger some kind of anti piracy lockout

[Some how this DC version of Atari Anniversary Edition works fine, but the GBA version of Atari Anniversary Advance also seems to work correctly in mGBA?](mgba-emu/mgba/issues/2432)

**Comment by qamichele594** [comment]
> > I have only tested 2 games so far but circle of the moon has severe audio lag and megaman zero has background screen tearing and severe slowdown when the flashcard was ina ds lite, and when inserted in a 3ds the bottom 5th on both screens are made up of 5 repeating rows in every gba game, but the cotm audio lag is gone, I just updated to the latest version of twilight menu
> 
> Audio issues are a known issue on DS Lite, it's better on DSi with Unlaunch/3DS since they can use the DSP processor for that.
> 
> The graphical issues with repeating lines are a bug in TWL_FIRM made worse by GBARunner2 messing with the frame rate in DSP builds, honestly the best solution is to just use VC Injects, open_agb_firm, or (only on n3DS) mGBA, GBARunner2 just isn't that great on 3DS as it's intended for DS/DSi.
> 
> The Sonic Advance issue isn't AP but rather it checking for the link cable, it works in Wi-Fi link builds, but for main builds you'll just need to patch the ROMs with the patch in [the compatibility list](https://wiki.gbatemp.net/wiki/GBARunner2/DSi_3DS_Compatibility_List), not sure about the rest of your issues though using a [proper BIOS dump](https://wiki.ds-homebrew.com/gbarunner2/bios) may help if you're not.
> 
> @michele559 can you at least keep your off topic spam to your own issues, if you legitimately want help/to help at least listen to what people say to you.

[There has a bug from other things in Hello Kitty Collection: Kitty the Kool! Kabuki de Tanoshiku Odotte Ne!! on PCSX-rearmed libretroVITA core?](https://github.com/libretro/pcsx_rearmed/issues/600)

**Comment by qamichele594** [comment]
[Someone this GBArunner2 is closed, just use VBA-M or open_agb_firm or VC Injects or (only on N3DS) mGBA3DS instead](https://github.com/Gericom/GBARunner2/issues/261)

**Comment by michele5943** [comment]
> > I have only tested 2 games so far but circle of the moon has severe audio lag and megaman zero has background screen tearing and severe slowdown when the flashcard was ina ds lite, and when inserted in a 3ds the bottom 5th on both screens are made up of 5 repeating rows in every gba game, but the cotm audio lag is gone, I just updated to the latest version of twilight menu
> 
> Audio issues are a known issue on DS Lite, it's better on DSi with Unlaunch/3DS since they can use the DSP processor for that.
> 
> The graphical issues with repeating lines are a bug in TWL_FIRM made worse by GBARunner2 messing with the frame rate in DSP builds, honestly the best solution is to just use VC Injects, open_agb_firm, or (only on n3DS) mGBA, GBARunner2 just isn't that great on 3DS as it's intended for DS/DSi.
> 
> The Sonic Advance issue isn't AP but rather it checking for the link cable, it works in Wi-Fi link builds, but for main builds you'll just need to patch the ROMs with the patch in [the compatibility list](https://wiki.gbatemp.net/wiki/GBARunner2/DSi_3DS_Compatibility_List), not sure about the rest of your issues though using a [proper BIOS dump](https://wiki.ds-homebrew.com/gbarunner2/bios) may help if you're not.
> 
> @michele559 can you at least keep your off topic spam to your own issues, if you legitimately want help/to help at least listen to what people say to you.

Now that it still replys message from #275 ?

**Comment by michele5943** [comment]
> > I have only tested 2 games so far but circle of the moon has severe audio lag and megaman zero has background screen tearing and severe slowdown when the flashcard was ina ds lite, and when inserted in a 3ds the bottom 5th on both screens are made up of 5 repeating rows in every gba game, but the cotm audio lag is gone, I just updated to the latest version of twilight menu
> 
> Audio issues are a known issue on DS Lite, it's better on DSi with Unlaunch/3DS since they can use the DSP processor for that.
> 
> The graphical issues with repeating lines are a bug in TWL_FIRM made worse by GBARunner2 messing with the frame rate in DSP builds, honestly the best solution is to just use VC Injects, open_agb_firm, or (only on n3DS) mGBA, GBARunner2 just isn't that great on 3DS as it's intended for DS/DSi.
> 
> The Sonic Advance issue isn't AP but rather it checking for the link cable, it works in Wi-Fi link builds, but for main builds you'll just need to patch the ROMs with the patch in [the compatibility list](https://wiki.gbatemp.net/wiki/GBARunner2/DSi_3DS_Compatibility_List), not sure about the rest of your issues though using a [proper BIOS dump](https://wiki.ds-homebrew.com/gbarunner2/bios) may help if you're not.
> 
> @michele559 can you at least keep your off topic spam to your own issues, if you legitimately want help/to help at least listen to what people say to you.

Dont use gbarunner2. Use openagbfirm or another emulator like mgba3ds instead.?

**Comment by michelemassa5599** [comment]
> > I have only tested 2 games so far but circle of the moon has severe audio lag and megaman zero has background screen tearing and severe slowdown when the flashcard was ina ds lite, and when inserted in a 3ds the bottom 5th on both screens are made up of 5 repeating rows in every gba game, but the cotm audio lag is gone, I just updated to the latest version of twilight menu
> 
> Audio issues are a known issue on DS Lite, it's better on DSi with Unlaunch/3DS since they can use the DSP processor for that.
> 
> The graphical issues with repeating lines are a bug in TWL_FIRM made worse by GBARunner2 messing with the frame rate in DSP builds, honestly the best solution is to just use VC Injects, open_agb_firm, or (only on n3DS) mGBA, GBARunner2 just isn't that great on 3DS as it's intended for DS/DSi.
> 
> The Sonic Advance issue isn't AP but rather it checking for the link cable, it works in Wi-Fi link builds, but for main builds you'll just need to patch the ROMs with the patch in [the compatibility list](https://wiki.gbatemp.net/wiki/GBARunner2/DSi_3DS_Compatibility_List), not sure about the rest of your issues though using a [proper BIOS dump](https://wiki.ds-homebrew.com/gbarunner2/bios) may help if you're not.
> 
> @michele559 can you at least keep your off topic spam to your own issues, if you legitimately want help/to help at least listen to what people say to you.

No, while i opening any rom(s) in mGBA3DS, it gives an error screen:
![20220409_110251](https://user-images.githubusercontent.com/102807164/162564878-f4a6d47c-1c1b-4af7-bc8a-6b365f4043d6.jpg)
And now every time while i reboot the system you will be:
```
 An error has occurred:
 
 Unable to mount CTRNAND or load the CTRNAND FIRM
  .
 Please use an external external one.
 
 Press any button to shutdown
```
And then fixed the ctrnand with corrupted content(s), but i can't inject after installing cia files in GodMode9, what the same spot as of this:
```
0:/cia/Ace_Lightning.cia
Error: MBR MBR is corrupt

(<A> to continue)
```
I have been pressed the A button, then it appeared:
```
Exception: Data Abort (4)
GodMode9 v2.1.1
2022-03-31 15:12:12
 
R00: 00000001 | R01: 00000098
R02: FFFFFFFF | R03: FFEEFFEE
R04: 00000094 | R05: 00000000
R06: 00000000 | R07: 00213232
R08: 00000000 | R09: FFFFFFFF
R10: FFFFFFFF | R11: 08061E79
R12: 00000000 | R13: 228BFFB8
R14: 00000000 | R15: 08000654
CPSR: 200000D7

Press POWER to turn off.
```
Every time while i try to launch any game you will be:
```
 An exception occurred
 
 Processor:       Arm9
 Exception type:  prefetch abort (svcBreak)
 
 R0     00000000       R1     00000000
 R2     090F9371       R3     00000000
 R4     00000000       R5     FFFFFFBF
 R6     00000000       R7     00000000
 R8     09865433       R9     080C4A40
 R10    00000000       R11    00000000
 R12    00000000       SP     080C4A30
 LR     08028A8F       PC     0808595C
 CPSR   60000020
 
 Press A to save the crash dump
 Press any other button to shutdown
```
I tried to disable arm11 exception handlers, and the error screen is different in:
```
 An error has occurred:
 
 Failed to apply 1 FIRM patch(es).
 
 Press any button to shutdown
```
And
```
 An error has occurred:
 
 Failed to apply 4 FIRM patch(es).
 
 Press any button to shutdown
```
Also i couldn't open open_agb_firm either:
```
 An error has occurred:
 
 The payload is invalid or corrupted.
 
 Press any button to shutdown
```
