### ISSUE TITLE
Gba runner not recognizing bin files

### ISSUE THREAD

**Issue by F3arM3** [Gericom/GBARunner2#270]
I dumped the gba castlevania games from the advance collection to use them in flash carts, but they dumped as bin files which work in an ez flash omega, but are not recognized in twilight menu/ gba runner, any tips on how to convert them to gba files (which apparently is a form of bin file) or get them to show up? TIA

**Comment by Epicpkmn11** [comment]
bin is just the most generic possible extension, all data on a computer is technically "bin" (binary) files.

From what I see it should be as simple as renaming the extension to `.gba`.

**Comment by F3arM3** [comment]
I tried that but for some reason it stays as a .bin

**Comment by qamichele594-2** [comment]
#192 Somehow is dead?

**Comment by qahellokitty5947** [comment]
Driver 3 (US+EU) runs ok until it gets into the Atari logo, when you will it eventually gives a crappy arm11 error screen. We don't know if using mGBA3DS v0.9.3. View for screenshots here:
![20220213_212547 1](https://user-images.githubusercontent.com/99000291/153773727-375809b8-cf1c-4519-a983-312975e75be2.jpg)

**Comment by qamichelemassa5859** [comment]
Reopen?
Yeah
