### ISSUE TITLE
This is Gbarunner2 dead?

### ISSUE THREAD

**Issue by qamichelemassa5859** [Gericom/GBARunner2#282]
is only a question

**Comment by SombrAbsol** [comment]
No, it is not. The last commit was in 2020, of course, but you should know that the developer is currently working on other projects.

**Comment by qamichelemassa5859** [comment]
> 

just use visualboyadvance instead.

**Comment by qamichelemassa5859** [comment]
#281

**Comment by SombrAbsol** [comment]
Because VisualBoyAdvance has a DS port? For your information, there are many people who prefer to play GBA games on DS rather than on computer.

**Comment by qamichelemassa5859** [comment]
LumaTeam/Luma3DS/issues/1645

**Comment by SombrAbsol** [comment]
I don't see the connection with GBARunner2.

**Comment by qamichelemassa5859** [comment]
#281 reply?

**Comment by Epicpkmn11** [comment]
> I don't see the connection with GBARunner2.

It's qamichele, he never makes sense. Just ignore him and unfollow the issue until this alt is banned too.

**Comment by qamichelemassa5859** [comment]
> > I don't see the connection with GBARunner2.
> 
> It's qamichele, he never makes sense. Just ignore him and unfollow the issue until this alt is banned too.

Not banned
