### ISSUE TITLE
GBARunner not working 

### ISSUE THREAD

**Issue by olivleger** [Gericom/GBARunner2#298]
trying to play gba games on my dsi and it just glitches out. heres some photos:
![gba runner 2](https://user-images.githubusercontent.com/121623982/209970156-f803184d-cf46-4209-b32a-3c9dc356ccb0.jpg)
![same but not](https://user-images.githubusercontent.com/121623982/209970165-59c60f8c-4f3d-448c-8319-b9869276e172.jpg)
sorry about the second one the size and the glare is bad i know. thats what you get for 10yr old cameras

**Comment by lxg1202** [comment]
power off in a while ,i think the screen would be clean.

**Comment by olivleger** [comment]
no I have already tried, someone else had same problem but their solution didn't work either.

**Comment by olivleger** [comment]
I have since traded my DSI for a 3ds so I will not require anymore advice.
EDIT: i bought another dsi so lets see if i have same problem

**Comment by olivleger** [comment]
fixed it by clicking settings icon and clicking reset
