### ISSUE TITLE
GBARunner2 doesn't start/shows "glitched" graphics on 3DS.

### ISSUE THREAD

**Issue by lbezos10** [Gericom/GBARunner2#299]
Goot afternoon. (Sorry for inaccuracies regarding timing due to regional timezone differences)

I have the latest Twilight Menu++ on the 2DS with an 128GB microSD card, formatted with 64KB of cluster size.

When launching GBA games through TwilightMenu++, (for example Pokémon FireRed in this case trimmed with GodMode9) the game either doesn't start (in this case shows a white screen after the launching animation) or when gbarunner2 starts, shows lines in the bottom of both screens.

This means the gbarunner2 UI, as well as the game's graphics, show the screen's line in the bottom as repeats further down where it's not supposed to be.

I tested this issue a bit and it seemed to go away when charging, however when fully charged, and the battery reaches some capacity percentages the symptoms appear again.

Side note: The second issue also appears when resetting the game through gbarunner2's UI.

Have a good day.

- lbezos10

**Comment by lbezos10** [comment]
After digging out the issue, i have found out that the second one is an intrisic defect of Nintendo's buggy coding. Not a gbarunner2 issue.

Sorry for bothering.

- lbezos10

**Comment by olivleger** [comment]
hello how do you fix this i have the same problem
