### ISSUE TITLE
Doesn't launch on 3ds in dsi mode

### ISSUE THREAD

**Issue by TriforceOfPwnage** [Gericom/GBARunner2#3]
Every time I launch gbarunner2 on my n3dsxl via TWLoader i get a red top screen and a white bottom screen with the word fail in the top left corner of the bottom screen.

**Comment by Gericom** [comment]
It means it couldn't initialize dldi for some reason.

**Comment by mariogamer2** [comment]
Getting the same error here, on a 2ds.

**Comment by Gericom** [comment]
Did you try the master branch? And is your sd card fat32 formatted with 4kb clusters. This is very important. 32 kb clusters don't work (I need to fix that)

**Comment by mariogamer2** [comment]
I think my sd is formated to 64k (used to be compatible with *9 tools).

Yes I'm using master.

**Comment by Gericom** [comment]
Reformat to 4k clusters

**Comment by mariogamer2** [comment]
I mistaken,my 3ds is actually in 32k. I'll format lather.

**Comment by mariogamer2** [comment]
Just formated to 4k. I'll try soon.

**Comment by mariogamer2** [comment]
4k is bugy with the 3ds itself...

booting with sd -› freeze
without sd and after,inserting it -› freeze
And when loading injected sudokuhax with GBARunner2 as boot.nds,it give the same thing.

**Comment by mariogamer2** [comment]
Booting with sd freeze with 4k.
Same when inserting after booting.
For injected sudokuhax with GBARunner2 as boot.nds,it give the same red screen.

**Comment by mariogamer2** [comment]
Does I re-format to 32k?

**Comment by Robz8** [comment]
No. GBARunner2 still needs 4k.

**Comment by mariogamer2** [comment]
Definitely,it is 4k who do this (the freeze)...

I'll have to wait for 32k fix.

**Comment by Gericom** [comment]
In the latest commit on the sound improve branch, the 32k issue should be fixed. But the arm9 read doesn't work with nds bootstrap, because it can't patch the irq dispatcher (there is none)

**Comment by mariogamer2** [comment]
I'll try it.

**Comment by mariogamer2** [comment]
Actually it's give the same color screen,but give "TEST" instead.

**Comment by Gericom** [comment]
Use it with a flashcard if possible

**Comment by mariogamer2** [comment]
Actually I cannot use my flashcard... (some min sd problem).

I'll wait.

**Comment by dogtopus** [comment]
The sound improve branch always freezes on TEST screen. No matter on DS or 3DS, flashcart or 3DS SD card, 4k cluster or 32k cluster.

**Comment by Robz8** [comment]
Try compiling the branch with ahezard's libnds.

**Comment by Gericom** [comment]
Why would that fix anything? @Robz8 And in the latest commit I completely removed libnds for the arm9 anyway

**Comment by Gericom** [comment]
I am gonna try doing dldi from arm 7 again (but differently than before). That should fix dsi sd support

**Comment by mariogamer2** [comment]
Thank @Gericom !

**Comment by Gericom** [comment]
Well, I tried doing arm 7 read again, but it's slower than arm 9 read it seems. It should work on 3ds though. You could try the dldi_from_arm7_again branch.

**Comment by mariogamer2** [comment]
Running the game work,but when choosing a character,it freeze. At least it work :)

**Comment by mariogamer2** [comment]
Ah in fact it was a random freeze,it work.

**Comment by mariogamer2** [comment]
Also does it is region free?

**Comment by Robz8** [comment]
It already is region free.

**Comment by mariogamer2** [comment]
Ok I'll try EUR version.

**Comment by mariogamer2** [comment]
So the issues is fixed? There's still some glitch and/or random freeze but it is normal (compatibility)

**Comment by dogtopus** [comment]
Tried latest arm7 dldi branch and it works on my AceKard RPG (on SD card). Seems that not only nds-bootstrap doesn't like dldi on arm9 side ;)

**Comment by Gericom** [comment]
There are no official regions on GBA, so region free does not exist

 The nds bootstrap problem is because the dsi sd is only accessible from arm 7, so when using it from arm9, it has to communicate with the arm 7, but since I don't have an irq handler, it can't patch it either. The problem with a couple of cards must be something else. They should work fine on arm9.

**Comment by mariogamer2** [comment]
Might sound stupid,but maybe it is possible to emulate the irq hanlder? (sorry I'm not good with GBA things)

**Comment by Gericom** [comment]
That's not how it works. I am running the gba code, so it uses the gba bios + the games interrupt dispatcher. Normal homebrews use the one from libnds which is detected and patched by nds-bootstrap.

**Comment by mariogamer2** [comment]
Ah ok.

**Comment by Robz8** [comment]
Can this be closed?

**Comment by Gericom** [comment]
Yep

**Comment by mariogamer2** [comment]
Is there a better compatibility now?

**Comment by Gericom** [comment]
There should be if you uncomment ARM7_DLDI although some people reported that it didn't work

**Comment by mariogamer2** [comment]
I need to run makefile_isnitro or not?
