### ISSUE TITLE
broken audio and video in doom 1 and doom II

### ISSUE THREAD

**Issue by olivleger** [Gericom/GBARunner2#305]
someone please help me. i wanted to play doom so i downloaded the rom on vimm . net and loaded it into my 32gb sd card now booted into the game it is very broken. running on latest version of gbarunner2 and twilight menu on dsi

**Comment by RocketRobz** [comment]
Please don't mention ROM sites by name.
Also, I'm pretty sure the DOOM games are known to have issues in GBARunner2.

**Comment by olivleger** [comment]
i wont mention rom sites in next posts and i will try different games later. thank you.
