### ISSUE TITLE
Play with pokemon roms gba

### ISSUE THREAD

**Issue by yamakachat** [Gericom/GBARunner2#35]
Gbarunner2 is included with twilight menu++ , i put bios.bin in root .
I can play some gba game but i can’t play with pokemon emerald pokemon ruby and pokemon saphir. Did someone get a fix?

**Comment by spyjoshx** [comment]
Most likely, you need to SRAM patch it. To do that you'll need GBATA. (Link: http://www.no-intro.org/tools.htm) Also, the version of GBARunner included with TwilightMenu++ is not the most recent, so it probably won't be able to save.
