### ISSUE TITLE
Adding bios.bin sha to readme

### ISSUE THREAD

**Issue by mariogamer2** [Gericom/GBARunner2#4]
This would help finding the good bios.

**Comment by Gericom** [comment]
Good point. I'll do that in the next commit

**Comment by piratesephiroth** [comment]
wouldn't a CRC32 be enough (and much faster to check if the file was downloaded in a zip/rar)

**Comment by mariogamer2** [comment]
Any SHA will do the thing.

**Comment by Gericom** [comment]
I can add all checksums you want, but that would be overkill

**Comment by piratesephiroth** [comment]
I think the CRC32 for the good GBA bios is 81977335

**Comment by mariogamer2** [comment]
Yep you'r right @piratesephiroth .

**Comment by aphirst** [comment]
Would it be beyond the scope of GBARunner2 to explicitly compare this CRC32 itself, e.g. when initially loading, or when trying to load a GBA backup?

**Comment by FlameAlt53** [comment]
so... 
This is just never gonna happen though it is fairly simple? (Its been almost 3 years, so I'm asking)

**Comment by Gericom** [comment]
Done in eda125e70953b150a22db2e10cbbc31e68ccbad0
