### ISSUE TITLE
Pokémon games support

### ISSUE THREAD

**Issue by impascal** [Gericom/GBARunner2#61]
I really like and support gbarunner2. The only thing that I request is when it will support main series pokémon games for gba, which are now basically unplayable.

**Comment by cotodevel** [comment]
I am working on a GBARunner2 branch that plays Pokémon Emerald (and thus, others) and it's being worked on. For the moment it only does DLDI at ARM9, and there at least the SD driver must be moved to fsfat.

**Comment by cotodevel** [comment]
I am working on a GBARunner2 branch that plays Pokémon Emerald (and thus, others) and it's being worked on. For the moment it only does DLDI at ARM9, and there at least the SD driver must be moved to fsfat so until that is not ready then codebase must be worked on.

**Comment by impascal** [comment]
oh, I hope to try it soon.

**Comment by Gericom** [comment]
This branch can play pokemon emerald (with sram patch): https://github.com/Gericom/GBARunner2/tree/feature/rom3M

**Comment by takeshineale128** [comment]
Tryed Pokémon emerald without a sram patch on the latest release the only issue I have is the rtc doesn't work.

**Comment by Gericom** [comment]
Yeah, that's one thing I still need to implement

**Comment by R-YaTian** [comment]
> Yeah, that's one thing I still need to implement

The LGFR(U)(CHS-Patched) roms will work good without SRAM patch on v20190822-153549_cfc6525.
But the latest release v20190824-234952_2dc841f always white screen after press start button screen.
It's so strange.And the wramicache version also have the problem.

**Comment by Gericom** [comment]
What is CHS patched?

**Comment by R-YaTian** [comment]
> What is CHS patched?
A Chinese translation version of the game.

**Comment by R-YaTian** [comment]
> What is CHS patched?

A Chinese translation version of the game.

**Comment by Gericom** [comment]
Oh, okay. Strange

**Comment by R-YaTian** [comment]
> Oh, okay. Strange

Will you look into it?
Are the two build of Gbar2 from different branch?

**Comment by Gericom** [comment]
Yeah, they are actually. So maybe that's the difference idk. Would have to merge the latest master into that branch

**Comment by R-YaTian** [comment]
> Yeah, they are actually. So maybe that's the difference idk. Would have to merge the latest master into that branch

Thanks a lot.
