### ISSUE TITLE
Pokémon Fire Red freeze after saving or after title screen

### ISSUE THREAD

**Issue by Marvo995** [Gericom/GBARunner2#65]
I'm testing GBARunner2 with my 2ds through a DS flashcard (R4 SDHC Dual Core) in DS mode.

Playing Pokémon FireRed European version with commit v20190819-165336_70aeb4d and v20190819-170100_0729ad2 (the latest two ones at the time of writing) gives me a freezing screen with music in loop right at the end of the saving process (that is,  the "PLAYERNAME has saved the data" message).
If you restart the game it resumes from where you last save (so despite the freeze it manages to complete the save) 
This also occasionally happen after you press start in the title screen, this time with a white screen and still a looping sound.
Every version (arm7/9- wramicache/not) is affected, while commit v20190818-142717_6609ad3 wasn't 

I hope this information can be of help

**Comment by Gericom** [comment]
Thanks for reporting, I'll have a look at it

**Comment by Gericom** [comment]
I've most likely found the bug. I forgot to add a jump when I removed a piece of code here: https://github.com/Gericom/GBARunner2/blob/70aeb4d49abe891207a9c5278cbac93d121df819/arm9/source/emu/irq.s#L331

I'll fix it as soon as I have time

**Comment by Marvo995** [comment]
I'm happy you managed to find the issue, thanks for the update

**Comment by Gericom** [comment]
I'll keep it open as long as I haven't fixed it
