### ISSUE TITLE
Application freezes when loading list of files

### ISSUE THREAD

**Issue by sloppycombo** [Gericom/GBARunner2#78]
Whenever I open a folder that contains files (.gba or .nds) the application freezes. Consequently if there is a "gba" directory present at the root with some roms in there the app freezes at startup. It does show the top purple bar with the label "GBARunner2" and the cog icon, but nothing works. As long as there's no "gba" folder at the root I can browse the file system until I try to open a folder with actual files.

I'm running it on my DSi XL using Hiyacfw + Twilight Menu. All latest, GBARunner2 and nds-bootstrap on the latest nightlies. The same behaviour also happened with the included GBARunner2 and nds-bootstrap in the latest Twilight Menu release. The bios checksum also checks out, but I suppose that isn't used during browsing.

I couldn't find anything like this problem, so I'm inclined to believe there's something wrong with my formatting. I've formatted my sd card with macOS, FAT32 using 4k cluster size. I can format it using Windows if needed, but I would prefer to just do it with my main OS. The sd card I'm using is a 4gb sdhc card, but I also have an old 1gb card. I have not formatted that with 4k cluster size, but it exhibits the same problem.

**Comment by RS55** [comment]
Have you tried the recommended cluster? (32kb)

**Comment by sloppycombo** [comment]
Thanks for your reply @RS55! Unfortunately reformatting with cluster size set to 32kb did not work. I also updated GBARunner2 to the version that just got released.

I would like to try and format my sd card using Windows. Any pointers on which tool and settings I should use for that?

On the ndshacks reddits page there is another user with the same problem. I have asked them if they're also on Mac.

**Comment by zenseii** [comment]
How many gba roms do you have in the same folder?

**Comment by sloppycombo** [comment]
Three. I also tried removing any characters that might trip up the app but that also didn't help (and I saw in screenshots that the characters should be fine).

**Comment by Gericom** [comment]
Hmm, interesting. I wonder what macos would do differently

**Comment by sloppycombo** [comment]
I have formatted the sd card using SD Formatter 5.01 on Windows (running as a vm). I also used Windows to copy the files on the card, and now GBARunner2 is working! The games look great on the DSi XL screen.

After that I tried copying some other games on there using macOS and now GBARunner2 is promptly freezing again. However, just mounting the card and unmounting is fine – after I reformatted it using Windows and copied the files again using Windows.

So the problem is definitely related to macOS, but maybe not necessarily to how macOS formats the card but how macOS writes the files. My knowledge about file systems and external media and the like is very limited so I can't think of anything that would cause this. I thought about trying the macOS version of the SD Formatter tool too but since the application is freezing even after writing my files after it was working using macOS I doubt the problem lies in the formatting. This is also the first time I've ever encountered an issue like this.

It would be nice if this problem could be fixed. @Gericom if you need me to test anything, let me know. For now maybe put something in the README about making sure to format and copy using Windows?

**Comment by Gericom** [comment]
Could it be related to all that hidden shit macos always makes in folders?

**Comment by sloppycombo** [comment]
That seems to be it! I was under the assumption that macOS only makes these files at the root level, and I could navigate the root just fine. You can view these files in Finder when enabling 'show hidden files'.

Turns out it also creates a ._{filename}.{extension} for every file. Showing hidden files in Finder does not show these. However using 'ls -a' in the terminal will list them. These are called [AppleDouble](https://en.wikipedia.org/wiki/AppleSingle_and_AppleDouble_formats) files.

Using 'dot_clean {pathToFolder}' will delete them and GBARunner2 doesn't freeze anymore when opening the folder.

**Comment by Gericom** [comment]
Ah, cool. I wonder why they cause problems and if it's a gbarunner2 thing or a problem in the FatFS library. Maybe you could try some things related to filenames starting with a dot and such.

**Comment by Gericom** [comment]
Okay, I think I fixed the issue in f52fe2bf9e2249c8d0e644e880885345edea5efc. It was first checking attributes of a file/directory before checking for end of directory. So if the last file was a hidden file (for example a ._ one), it would keep looping. Please let me know if it works!

**Comment by sloppycombo** [comment]
I'll give it a try tonight!

**Comment by Gericom** [comment]
I believe this was fixed
