### ISSUE TITLE
Having trouble installing the latest release of gbarunner2

### ISSUE THREAD

**Issue by osiristech** [Gericom/GBARunner2#81]
Having trouble installing the latest release of gbarunner2

**Comment by zenseii** [comment]
Can you specify what happens? Are you able to get into the menu? What console?

**Comment by osiristech** [comment]
DSI No when I try to load gbarunner from the game menu it just goes white.

**Comment by zenseii** [comment]
Is there any text? Are you running it from twilightmenu?

**Comment by osiristech** [comment]
When I replaced the NDs files for gbarunner and tried to load it,  the screen went white
