### ISSUE TITLE
Game freeze during intro - Mario & Luigi: Superstar Saga (USA)

### ISSUE THREAD

**Issue by bryc** [Gericom/GBARunner2#84]
Tested using  0c697a9 on a DS Lite.

It consistently freezes when encountering Bowser during the new game intro sequence. Mario says "Let's go" to start the first battle and then it stalls.

**Comment by Gericom** [comment]
Disable main memory cache

**Comment by Alexboy2334** [comment]
I have the same problem. I tried to fix it by disabling the main memory icache, but the sprites don't work as they should and I can see every frame of the game. https://github.com/Gericom/GBARunner2/issues/175

**Comment by LazyKoala24** [comment]
> I have the same problem. I tried to fix it by disabling the main memory icache, but the sprites don't work as they should and I can see every frame of the game. #175

Same here

**Comment by thanone2** [comment]
How do you disable main memory cache?
