### ISSUE TITLE
gyro not working on 3DS with TWiLight Menu++

### ISSUE THREAD

**Issue by assmunch789** [Gericom/GBARunner2#85]
tried both Wario Ware Twisted and Yoshi's Topsy Turvy and they don't recognize the gyro. does anyone have a fix for this or am I kaput?

**Comment by Gericom** [comment]
You need a build of the special branch and the rtcom patched twlbg module. Only the gyro of wario ware twisted is currently supported, and the way it works is wrong atm.

**Comment by assmunch789** [comment]
and where can I get that?

**Comment by Gericom** [comment]
You should be able to patch a twlbg you dump from your 3ds with sonos patcher

**Comment by ObscureExtractor** [comment]
There is some delay with audio with this build
