### ISSUE TITLE
(feature request) fix full screen error of Metroid Zero Mission, Mother 3,Dragon Ball Advence Adventure and Kingdom Hearts Chains of Memories on dsi (and a few suggestions)

### ISSUE THREAD

**Issue by CaioMel360** [Gericom/GBARunner2#88]
The games mentioned are not fully full screen, they get bugged

Suggestions: Add on the button screen some options like save state, load state, volume options (because my guess is broken and the game volume is very high), frame advancement brightness options,you can have a choice of X and Y buttons becoming shortcuts (you could choose which ones) or turbo buttons or even screenshots or cheat support.I'm saying that  because users like us have to have a lot of options, not just push a button and play,you understand it?

**Comment by zenseii** [comment]
"You understand it?" I'll give you the benefit of the doubt and language, but this way of expressing yourself comes off as very ungrateful. Please try to show more modesty and not sound like you're demanding this. Gericom is doing this for free.

**Comment by CaioMel360** [comment]
> "Você entende isso?" Darei a você o benefício da dúvida e da linguagem, mas essa maneira de se expressar se mostra muito ingrata. Por favor, tente mostrar mais modéstia e não pareça estar exigindo isso. A Gericom está fazendo isso de graça.

sorry, i'm using the translator, i know he's doing it for free but i didn't want you to misunderstand me,I meant that if he understands what I mean, I never thought in a thankless way, he's doing his best, I know it's not easy to do everything I'm talking about

**Comment by Gericom** [comment]
Yeah, I cannot understand everything you are saying, but an ingame menu is planned, but is just quite some work to implement, and I don't have a lot of time at the moment. As for how things look when you disable borders, I am not the one who controls how that looks (it is just a side effect of using ds 2d hardware). It may be more something for rom hackers to try to make patches for the game to make it look better (if possible at all).
