### ISSUE TITLE
Little issue with Super Mario Advance

### ISSUE THREAD

**Issue by JORGETECH** [Gericom/GBARunner2#90]
The system hangs when trying to access the Mario Bros. minigame in Super Mario Advance. Tested with a DSi, EU ROM and with the next options set:

- Enable border frame
- Enable center and mask
- Enable DS main memory i-cache
- Enable wram i-cache
(Changing cache options have no effect)

**Comment by borb** [comment]
Yet oddly the same minigame works when started from Super Mario World (SMA2).

**Comment by RobertPeip** [comment]
When starting this minigame in SMB it reads in the bios area and expects to readback the correct, old hold-value, otherwise it hangs up. Could be the reason here.

**Comment by Gericom** [comment]
Ah, interesting. I am currently always using the one that would normally be read after swi execution. I should implement it such that the right values are set by the irq and swi handler. That might fix it

**Comment by RobertPeip** [comment]
At least one game even depends on the value right after exiting bios (0xE129F000) : "Wakeboarding Unleashed featuring Shaun Murray"

have seen that on your compatibility list.
Maybe you can also implement that value.
