### ISSUE TITLE
TW 11.2 can't run GBARunner2

### ISSUE THREAD

**Issue by david-zzj** [Gericom/GBARunner2#96]
I had update to TW 11.2 as usual, when i open GBARunner2 from the title, it gave me a white screen and freeze. I changed to TW 11.0 all goes well.

**Comment by RocketRobz** [comment]
Try TWLMenu++ 11.2.0 with the GBARunner2 build from v11.0.0.

**Comment by david-zzj** [comment]
Ok, i try later and feedback here.

**Comment by RocketRobz** [comment]
@Gericom There's has been no reply so far. Can this be closed?

**Comment by Gericom** [comment]
Yeah I guess so

**Comment by david-zzj** [comment]
Sorry reply so late,  the new version of gbarunner can run correctly,
THX.
