### ISSUE TITLE
The Nds X button

### ISSUE THREAD

**Issue by brandflake11** [Gericom/GBARunner2#97]
Hello,

This is an amazing piece of software, thank you so much for the work on it. Is there a way to disable the x button during GBA gameplay? The X button, when pressed, makes games that I have tried on my new 3dsxl, with Twilightmenu, glitch and sometimes lose music. What would I need to change in the code to disable the x button, if it is a feature?

Thank you very much for your time!

**Comment by piratesephiroth** [comment]
Yeah it's a button specifically made for glitching the games.
Gericom worked very hard to make it really ruin the experience, please be thankful.

**Comment by zenseii** [comment]
> Hello,
> 
> This is an amazing piece of software, thank you so much for the work on it. Is there a way to disable the x button during GBA gameplay? The X button, when pressed, makes games that I have tried on my new 3dsxl, with Twilightmenu, glitch and sometimes lose music. What would I need to change in the code to disable the x button, if it is a feature?
> 
> Thank you very much for your time!

It's there in order to resync sound in case it gets desynced. For the moment there's probably no easy way to disable it, but I imagine that it's only gonna be there so long as sound desync is a problem.

**Comment by brandflake11** [comment]
> > Hello,
> > This is an amazing piece of software, thank you so much for the work on it. Is there a way to disable the x button during GBA gameplay? The X button, when pressed, makes games that I have tried on my new 3dsxl, with Twilightmenu, glitch and sometimes lose music. What would I need to change in the code to disable the x button, if it is a feature?
> > Thank you very much for your time!
> 
> It's there in order to resync sound in case it gets desynced. For the moment there's probably no easy way to disable it, but I imagine that it's only gonna be there so long as sound desync is a problem.

Thank you for the heads up on this! If it helps to report this, it does break music on Warioware.

**Comment by Gericom** [comment]
Yeah, it is not a bug. It is meant for resyncing sound and not for pressing it all the time :p. Hotkeys will likely be configurable at some point.
